build:
  - image: node:10.15.0
    commands:
      - ["node", "--version"]
      - ["npm", "--version"]
  - image: alpine
    dir: pkg
    command: ["pwd"]
  - image: alpine
    commands:
      - ["apk", "update"]
  - image: alpine
    commands:
      - ["printenv"]
    envs:
      - PERM=775
      - ID=dunner
      - DIR=`$HOME`
  - name: '@show'
    args:
      - '/root'
show:
  - image: alpine
    commands:
      - ["ls", "$1"]
    mounts:
      - '~/Downloads:/root/down'
      - ~/Pictures:/root/pics:wr
      - "~/Documents:/root/docs:r"