envs:
  - VAR1=VAL1
  - GLB=VARBL
mounts:
  - ./pkg:/tmp:r
tasks:
  build:
    envs:
      - VAR1=VAL11
      - VAR2=VAL2
    mounts:
      - ./pkg/dunner:/tmp:r
    steps:
      - image: node:10.15.0
        commands:
          - ["node", "--version"]
          - ["npm", "--version"]
      - image: alpine
        dir: pkg
        command: ["pwd"]
      - image: alpine
        commands:
          - ["ls", "/tmp"]
      - image: alpine
        commands:
          - ["printenv"]
        envs:
          - VAR2=VAL22
          - PERM=775
          - ID=dunner
          - DIR=`$HOME`
      - follow: 'show'
        args:
          - '/tmp'
  show:
    steps:
      - image: alpine
        commands:
          - ["printenv"]
          - ["ls", "$1"]
        mounts:
          - '~/Downloads:/root/down'
          - ~/Pictures:/root/pics:wr
          - "~/Documents:/root/docs:r"