build:
  - image: node:10.15.0
    command: ["node", "--version"]
  - image: node:10.15.0
    command: ["npm", "--version"]
  - image: alpine
    dir: pkg
    command: ["pwd"]
  - image: alpine
    command: ["apk", "update"]
  - image: alpine
    command: ["printenv"]
    envs:
      - PERM=775
      - ID=dunner
      - DIR=`$HOME`
  - image: alpine
    command: ["ls", "/root"]
    mounts:
      - '~/Downloads:/root/down'
      - ~/Pictures:/root/pics:wr
      - "~/Documents:/root/docs:r"