# Goreleaser documentation at http://goreleaser.com
project_name: dunner
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64

archives:
- replacements:
    386: i386
    amd64: x86_64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
    - Update readme
snapshot:
  name_template: "{{.ProjectName}}_{{.Tag}}"

release:
  draft: true
  name_template: "{{.ProjectName}} v{{.Version}}"

brew:
  github:
    owner: leopardslab
    name: homebrew-dunner
  folder: Formula
  homepage:  https://github.com/leopardslab/Dunner
  description: A Docker based task runner tool
  test: |
    system "#{bin}/dunner version"

nfpm:
  name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  homepage:  https://github.com/leopardslab/Dunner
  description: A Docker based task runner tool
  maintainer: LeopardsLab Community
  license: MIT
  formats:
  - deb
  - rpm

