language: go
go:
  - 1.11.x
  - 1.12.x
  - master
env:
  global:
    - DEP_VERSION="0.5.0"
services:
  - docker
addons:
  apt:
    packages:
      - rpm
      - snapd
  homebrew:
    packages:
      - dep
    update: true
before_install:
  - openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv
    -in snap.login.enc -out snap.login -d
  - if [ $TRAVIS_OS_NAME = linux ]; then echo "Installing dep"; curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then chmod +x $GOPATH/bin/dep; fi
install:
  - make setup
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo snap install snapcraft --classic; fi
script:
  - make ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [ $TRAVIS_OS_NAME = linux ]; then if test -n "$TRAVIS_TAG" && snapcraft login --with snap.login; fi
matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode10
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    verbose: true
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
      master: true
