language: go

go:
- 1.11.x
- master

services:
  - docker

env:
  global:
  - DEP_VERSION="0.5.0"
  - PATH=/snap/bin:$PATH

services:
- docker
addons:
  apt:
    update: true
    packages:
    - rpm
    - snapd

before_install:
- rpmbuild --version
- sudo apt-get update
- sudo apt-get install -y rpm
- rpmbuild --version
- openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv
  -in snap.login.enc -out snap.login -d
- curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64
  -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep

install:
- make setup
- sudo snap install snapcraft --classic

script:
- make ci

after_success:
- bash <(curl -s https://codecov.io/bash)
- test -n "$TRAVIS_TAG" && snapcraft login --with snap.login

deploy:

- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash -s -- --config=.snap_goreleaser.yml --rm-dist
  verbose: true
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
    master: true

- provider: script
  skip_cleanup: true
  script: $GOPATH/bin/dunner do release_dunner -t release/.dunner.yaml
  verbose: true
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
    master: true