language: go

go:
  - "1.11.x"
  - master

env:
  - DEP_VERSION="0.5.0"

services:
  - docker

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure -v

script:
  - go test ./...  -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)