language: go

go:
  - "1.11.x"
  - master

env:
  - DEP_VERSION="0.5.0"

services:
  - docker
addons:
  apt:
    packages:
    - rpm
    - snapd
env:
  - PATH=/snap/bin:$PATH

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - dep version

install:
  - dep ensure -v
  - sudo snap install snapcraft --classic

script:
  - make ci

after_success:
  - test -n "$TRAVIS_TAG" && snapcraft login --with snap.login

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  verbose: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
    master: true