name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1

    - name: Build Dunner and run tests on linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        echo $GOBIN
        echo $GOPATH
        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        dep ensure
        go install
        dunner version
        dunner do show

    - name: Build Dunner and run tests on Mac
      if: matrix.os == 'macOS-latest'
      run: |
        brew install dep
        brew upgrade dep
        dep ensure
        go install
        dunner version
        dunner do show
