name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Build Dunner and run tests
      run: |
        go get -d -u github.com/golang/dep
        dep ensure
        go install
        dunner version
        dunner do show
