name: Dunner CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: '1.11.x'
    - name: Build Dunner and run unit tests
      run: |
        echo $GOPATH
        echo $GOBIN
        ls -al $GOPATH
        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        dep ensure
        make setup
        make ci
        make build
        dunner version
        dunner do show