name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build Dunner using Dunner
      run: |
        curl https://installer.to/dunner | bash
        dunner version
        dunner do build
