name: Dunner CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.11.x'

    - name: Checkout Dunner
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: go/src/github.com/leopardslab/dunner

    - name: Debug
      if: matrix.os == 'windows-latest'
      run: |
        pwd
        echo home: %HOME%
        echo workspace: %GITHUB_WORKSPACE%
        echo gopath: %GOPATH%
        echo goroot: %GOROOT%
        go env GOPATH
        ls %GOPATH%
        ls -l

    - name: Debug
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'
      run: |
        pwd
        echo $HOME
        echo $GITHUB_WORKSPACE
        echo $GOPATH
        echo $GOROOT
        go env GOPATH
        ls $GOPATH
        ls -l

    - name: Build Dunner and run unit tests
      if: matrix.os == 'ubuntu-latest'
      env:
        GOPATH: /home/runner/work/dunner/go
      run: |
        mkdir -p $(go env GOPATH)/bin
        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        $(go env GOPATH)/bin/dep ensure -v
        make setup
        make ci
        $GOPATH/bin/dunner version
        $GOPATH/bin/dunner do show

    - name: Build Dunner and run unit tests
      if: matrix.os == 'macOS-latest'
      env:
        GOPATH: /Users/runner/runners/2.157.3/work/dunner/go # FIXME: Remove this hard coded path value
      # Not running unit tests in mac since there is no docker support
      run: |
        brew install dep
        dep ensure -v
        make setup DEP=dep
        make fmt lint vet
        make install DEP=dep
        $GOPATH/bin/dunner version
        $GOPATH/bin/dunner do show


    - name: Build Dunner and run unit tests
      if: matrix.os == 'windows-latest'
      env:
        GOPATH: d:\a\dunner\go\
      run: |
        mkdir -p $(go env GOPATH)\bin
        choco install dep
        dep ensure -v
        make setup DEP=dep
        make fmt lint vet
        go test -v ./...
        %GOPATH%bin\dunner version
        %GOPATH%bin\dunner do show
